project:
  type: website
  output-dir: docs

website:
  title: "Jonathan Ye's Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Projects.qmd
        text: Projects
      - href: research.qmd
        text: Research

format:
  html:
    theme: minty
    css: styles.css
    toc: true



