project:
  type: website
  output-dir: docs

website:
  title: "Jonathan Ye's Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: example_analysis.qmd
        text: Example Analysis

format:
  html:
    theme: minty
    css: styles.css
    toc: true



